jmose_command_scheduler_list:
    path:  /command-scheduler/list
    defaults: { _controller: JMoseCommandSchedulerBundle:List:index }

jmose_command_scheduler_monitor:
    path:  /command-scheduler/monitor
    defaults: { _controller: JMoseCommandSchedulerBundle:List:monitor }

jmose_command_scheduler_action_toggle:
    path:  /command-scheduler/action/toggle/{id}
    defaults: { _controller: JMoseCommandSchedulerBundle:List:toggle }

jmose_command_scheduler_action_remove:
    path:  /command-scheduler/action/remove/{id}
    defaults: { _controller: JMoseCommandSchedulerBundle:List:remove }

jmose_command_scheduler_action_execute:
    path:  /command-scheduler/action/execute/{id}
    defaults: { _controller: JMoseCommandSchedulerBundle:List:execute }

jmose_command_scheduler_action_unlock:
    path:  /command-scheduler/action/unlock/{id}
    defaults: { _controller: JMoseCommandSchedulerBundle:List:unlock }

jmose_command_scheduler_detail_index:
    path:  /command-scheduler/detail/view/
    defaults: { _controller: JMoseCommandSchedulerBundle:Detail:index }

jmose_command_scheduler_detail_edit:
    path:  /command-scheduler/detail/edit/{scheduledCommandId}
    defaults: { _controller: JMoseCommandSchedulerBundle:Detail:initEditScheduledCommand }

jmose_command_scheduler_detail_new:
    path:  /command-scheduler/detail/new
    defaults: { _controller: JMoseCommandSchedulerBundle:Detail:initNewScheduledCommand }

jmose_command_scheduler_detail_save:
    path:  /command-scheduler/detail/save
    defaults: { _controller: JMoseCommandSchedulerBundle:Detail:save }
