services:
    jmose_command_scheduler.command_parser:
        class: JMose\CommandSchedulerBundle\Service\CommandParser
        arguments:
            - "@kernel"
            - "%jmose_command_scheduler.excluded_command_namespaces%"

    jmose_command_scheduler.form.type.command_choice:
        class: JMose\CommandSchedulerBundle\Form\Type\CommandChoiceType
        arguments:
            - "@jmose_command_scheduler.command_parser"
        tags:
            - { name: form.type, alias: command_choice }
