namespaces:
    CommandSchedulerConstraints: JMose\CommandSchedulerBundle\Validator\Constraints\

JMose\CommandSchedulerBundle\Entity\ScheduledCommand:
    properties:
        cronExpression:
            - NotBlank: ~
            - CommandSchedulerConstraints:CronExpression: { message: "commandScheduler.validation.cron" }
        name:
            - NotBlank: ~
        command:
            - NotBlank: ~
        priority:
            - Type: { type: 'integer'}

